name: habit_note
description: A notepad and image to text converter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  audioplayers: ^0.20.1
  bottom_navy_bar: ^6.0.0
  camera: ^0.9.4+19
  cached_network_image: ^3.2.0
  clipboard: ^0.1.2+8
  cupertino_icons: ^1.0.4
  file_picker: ^4.4.0
  flutter_markdown: ^0.6.9+1
  flutter_mobx: ^2.0.4
  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  material_tag_editor: ^0.1.2
  mobx: ^2.0.6+1
  nb_utils: ^4.4.14
  provider: ^6.0.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.0.20

  # FIREBASE PACKAGES
  cloud_firestore: ^3.1.10
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  firebase_storage: ^10.2.9

  # AUTHENTICATION
  google_sign_in: ^5.2.4
  google_fonts: ^2.3.1
  the_apple_sign_in: ^1.1.1
  mailer: ^5.1.0

  # PUSH NOTIFICATION
  flutter_local_notifications: ^9.4.0

  # UI
  confetti: ^0.6.0
  flutter_staggered_grid_view: ^0.6.1
  page_transition: ^2.0.5

  # TEXT RECOGNITION
  google_ml_kit: ^0.7.3
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.1
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.8
  mobx_codegen: ^2.0.5+2
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter_native_splash:
  color: "#ffb347"
  image: assets/images/splash.png
  color_dark: "#ffb347"
  image_dark: assets/images/splash.png
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/images/play_store_512.png"
  adaptive_icon_background: "#ffb347"

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/google_fonts/Lato/
   - assets/google_fonts/Fugaz_One/
   - assets/terms_of_use.md
   - assets/privacy_policy.md
   - assets/about_app.md
   - assets/sfx/
