// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaoonGW96sNje7c7qbfTbCzUSOdtEEPD4',
    appId: '1:785713279686:web:ecc5b2c08844a78e42ddc7',
    messagingSenderId: '785713279686',
    projectId: 'flutter-habit-note',
    authDomain: 'flutter-habit-note.firebaseapp.com',
    storageBucket: 'flutter-habit-note.appspot.com',
    measurementId: 'G-28F3FGZ9Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqd9HIi3nsYKp5zQQx4zK5mNCwvL4JcsQ',
    appId: '1:785713279686:android:14066a207b940a5f42ddc7',
    messagingSenderId: '785713279686',
    projectId: 'flutter-habit-note',
    storageBucket: 'flutter-habit-note.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZf6Jfs4-cCkBJestmGrTBjJ4DAoq81Aw',
    appId: '1:785713279686:ios:2fe133d4778375ba42ddc7',
    messagingSenderId: '785713279686',
    projectId: 'flutter-habit-note',
    storageBucket: 'flutter-habit-note.appspot.com',
    androidClientId: '785713279686-7a6bvmi304bmfltgjdfdko0f1cnorpm5.apps.googleusercontent.com',
    iosClientId: '785713279686-kuurnc67nltes8tfgg34unhoci2la8a2.apps.googleusercontent.com',
    iosBundleId: 'com.habit.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZf6Jfs4-cCkBJestmGrTBjJ4DAoq81Aw',
    appId: '1:785713279686:ios:2fe133d4778375ba42ddc7',
    messagingSenderId: '785713279686',
    projectId: 'flutter-habit-note',
    storageBucket: 'flutter-habit-note.appspot.com',
    androidClientId: '785713279686-7a6bvmi304bmfltgjdfdko0f1cnorpm5.apps.googleusercontent.com',
    iosClientId: '785713279686-kuurnc67nltes8tfgg34unhoci2la8a2.apps.googleusercontent.com',
    iosBundleId: 'com.habit.note',
  );
}
